### PR TITLE
Update CFP/CFT text

### PR DESCRIPTION
**Pull request by tghosth**

### CODE REVIEW

**Comment by tghosth** [comment]
Hi @eoftedal I created a new PR with some minor tweaks but otherwise all good, thanks :)

**Comment by eoftedal** [comment]
The headlines should be ## instead of ### as they are second level. If you think the font is to large for ## we should tweak the size instead.

**Comment by tghosth** [comment]
Ok @eoftedal I have changed the headings to ##. Could you make the size a little smaller as I don't know how, Thanks :)

**Comment by eoftedal** [comment]
@tghosth Done

**Pull request merged**
