### PR TITLE
CoC updates

### PR DESCRIPTION
**Pull request by oritro**
Added CoC full and short

### CODE REVIEW

**Comment by oritro** [comment]
Updated Menus.yml file

**Comment by eoftedal** [comment]
@oritro Please always write the headings with proper casing. If we want the headings upper cased, we do that with CSS (text-transform: uppercase).

**Comment by eoftedal** [comment]
Regarding CoC.md.
Either this should be written in markdown, or it should be a .html file. The title in the front matter will be added to the top of the page, so there is no need to add a separate `<h2>` below. The `<h3>`s should be `<h2>` as they are secondary headings.
Finally the file should be called code-of-conduct.md (or .html) to get a better URL (also improves search results in search engines).

**Comment by oritro** [comment]
updates per @eoftedal comments

**Comment by oritro** [comment]
update about menu to new url
update to the short version of coc page name

**Comment by oritro** [comment]
updated formating

**Pull request merged**
